codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "65...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "src/lib/Services/BaseService.js"
  - "src/lib/Services/JoinService.js"
  - "tests"  # can use regexp
  - "adocs"  # can use regexp
  - "coverage"
  - ".nyc_output"
  - "scripts"
