language: node_js
node_js:
- "stable"
env:
  - MOZ_HEADLESS=1
  
addons:
  firefox: "latest"
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "firefox --version"
  - "sleep 3"

after_success: npm run coverage
